# Generated by Django 4.2.6 on 2024-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0051_delete_deletedcustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsubcategory',
            old_name='description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='description_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='description_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
