# Generated by Django 4.2.6 on 2024-01-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0053_subsubcategory_price_1_subsubcategory_price_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='job_title',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('painter', 'Painter'), ('Tester', 'Tester'), ('Operator', 'Operator'), ('driver', 'Delivery Driver')], default='select title', max_length=20),
        ),
    ]
