# Generated by Django 4.2.6 on 2024-02-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0055_booking_pickup_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsubcategory',
            old_name='description_1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='price_5',
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, null=True),
        ),
    ]
