# Generated by Django 4.2.6 on 2024-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0056_rename_description_1_subsubcategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='skill',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='qualification_certificates/'),
        ),
    ]
