# Generated by Django 4.2.6 on 2024-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0058_booking_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
