# Generated by Django 4.2.6 on 2024-03-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0065_progressphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressPhoto',
        ),
    ]
