# Generated by Django 4.2.6 on 2024-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0067_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(to='vehicle.itemprice'),
        ),
    ]
