# Generated by Django 4.2.6 on 2024-03-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0069_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
